"""Internal Pydantic models for the TI ingestion pipeline.

These models define the data contract between pipeline stages:

    Fetcher  →  RawTTPRecord
    Normalizer  →  NormalizedTTPRecord  (+ NormalizedMarkerRecord)
    Validator   →  NormalizedTTPRecord  (same type, validated)
    Deduplicator / Upsert consume NormalizedTTPRecord directly.

These models are NOT exposed via the API.  The API-facing schemas live in
``app.schemas.threat_intelligence_schema``.
"""
from __future__ import annotations

import re
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator

# Regex for MITRE ATT&CK technique IDs (main + sub-technique).
_MITRE_ID_RE = re.compile(r"^T\d{4}(\.\d{3})?$")

# Controlled vocabulary: ingestion_source values that map to the ttps.source column.
VALID_SOURCES = frozenset({"manual", "mitre_attack", "misp", "malwarebazaar", "otx"})

# Per-source default confidence scores (set by Normalizer, not DB default).
SOURCE_DEFAULT_CONFIDENCE: dict[str, float] = {
    "manual":        1.00,
    "mitre_attack":  0.85,
    "misp":          0.50,
    "malwarebazaar": 0.40,
    "otx":           0.60,
}

# ATT&CK tactic → FraudShield category mapping.
# Only Android/Mobile ATT&CK tactics are listed.  Unknown tactics fall
# through to "uncategorized" and are flagged by the validator (V3).
TACTIC_TO_CATEGORY: dict[str, str] = {
    "credential-access":  "credential_theft",
    "collection":         "credential_theft",
    "persistence":        "persistence",
    "defense-evasion":    "evasion",
    "command-and-control": "c2_communication",
    "lateral-movement":   "propagation",
    "impact":             "device_control",
    "initial-access":     "social_engineering",
    "discovery":          "reconnaissance",
    "execution":          "evasion",      # Dynamic code execution → evasion bucket
    "network-effects":    "c2_communication",
    "remote-service-effects": "device_control",
    # Aliases used by some STIX bundles
    "credential access":  "credential_theft",
    "defense evasion":    "evasion",
    "command & control":  "c2_communication",
    "initial access":     "social_engineering",
}

# Allowed categories in the ttps.category column (existing + new from mapping).
ALLOWED_CATEGORIES = frozenset({
    "credential_theft",
    "device_control",
    "evasion",
    "persistence",
    "propagation",
    "social_engineering",
    "c2_communication",
    "reconnaissance",
})

# Allowed signal_type values (mirrors the DB CHECK constraint).
ALLOWED_SIGNAL_TYPES = frozenset({"api_signature", "permission", "manifest_component", "certificate"})

# Allowed match_mode values (mirrors the DB CHECK constraint).
ALLOWED_MATCH_MODES = frozenset({"exact", "substring", "regex"})


class NormalizedMarkerRecord(BaseModel):
    """A detection marker proposed by a source feed for insertion."""

    signal_type: str
    match_value: str
    match_mode: str = "substring"
    bucket: str
    severity: float = Field(ge=0.0, le=1.0, default=0.25)
    requires_context: bool = False
    external_id: Optional[str] = None
    source_reference: Optional[str] = None


class NormalizedTTPRecord(BaseModel):
    """Normalised, source-agnostic TTP ready for validation and upsert.

    The ``external_id`` field is the deduplication key. Every record from an
    automated source MUST have a non-empty external_id.  For manual records
    (admin UI) it may be None.

    ``db_id`` is the primary-key value that will be written to ``ttps.id``.
    It is generated by the Normalizer using ``generate_ttp_pk()`` and must
    conform to the ``^TTP-[A-Z0-9-]+$`` pattern enforced by the existing
    schema.
    """

    # Database PK (generated by Normalizer; fits ttps.id pattern)
    db_id: str
    # Human-readable identity
    name: str
    description: str
    # Classification
    category: str
    mitre_technique_id: Optional[str] = None
    mitre_tactic: Optional[str] = None
    # Provenance (maps to ttps.source column vocabulary)
    source: str
    source_reference: Optional[str] = None
    # Quality signals (set per-source by Normalizer)
    confidence_score: float = Field(ge=0.0, le=1.0, default=0.85)
    # Deduplication key from the source feed
    external_id: Optional[str] = None
    # Indicators written to ttps.indicators JSONB column
    indicators: list[str] = Field(default_factory=list)
    # Markers proposed for insertion into detection_markers
    proposed_markers: list[NormalizedMarkerRecord] = Field(default_factory=list)
    # Raw source payload — stored in quarantine on validation failure
    raw_payload: dict[str, Any] = Field(default_factory=dict)

    @field_validator("mitre_technique_id")
    @classmethod
    def _validate_technique_id(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and not _MITRE_ID_RE.match(v):
            raise ValueError(f"Invalid MITRE technique ID: {v!r}")
        return v
