"""Add analysis_stages to apk_submissions

Revision ID: fc3b3e1b0973
Revises: 0006
Create Date: 2026-08-09 16:00:19.943328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc3b3e1b0973'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_sha256', table_name='apk_submissions')
    op.drop_index('ix_submissions_status', table_name='apk_submissions')
    op.drop_index('ix_submissions_uploaded_by', table_name='apk_submissions')
    op.create_index(op.f('ix_apk_submissions_sha256_hash'), 'apk_submissions', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_apk_submissions_status'), 'apk_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_apk_submissions_uploaded_by'), 'apk_submissions', ['uploaded_by'], unique=False)
    op.add_column('apk_submissions', sa.Column('analysis_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('campaign_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cluster_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dynamic_findings', 'run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('dynamic_findings_submission_id_key', 'dynamic_findings', type_='unique')
    op.create_index(op.f('ix_dynamic_findings_submission_id'), 'dynamic_findings', ['submission_id'], unique=True)
    op.alter_column('llm_reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('llm_reports_submission_id_key', 'llm_reports', type_='unique')
    op.create_index(op.f('ix_llm_reports_submission_id'), 'llm_reports', ['submission_id'], unique=True)
    op.drop_constraint('ml_scores_submission_id_key', 'ml_scores', type_='unique')
    op.create_index(op.f('ix_ml_scores_submission_id'), 'ml_scores', ['submission_id'], unique=True)
    op.drop_constraint('risk_verdicts_submission_id_key', 'risk_verdicts', type_='unique')
    op.create_index(op.f('ix_risk_verdicts_submission_id'), 'risk_verdicts', ['submission_id'], unique=True)
    op.alter_column('static_findings', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('static_findings_submission_id_key', 'static_findings', type_='unique')
    op.create_index(op.f('ix_static_findings_submission_id'), 'static_findings', ['submission_id'], unique=True)
    op.alter_column('virustotal_lookups', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('virustotal_lookups_submission_id_key', 'virustotal_lookups', type_='unique')
    op.create_index(op.f('ix_virustotal_lookups_submission_id'), 'virustotal_lookups', ['submission_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virustotal_lookups_submission_id'), table_name='virustotal_lookups')
    op.create_unique_constraint('virustotal_lookups_submission_id_key', 'virustotal_lookups', ['submission_id'])
    op.alter_column('virustotal_lookups', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_static_findings_submission_id'), table_name='static_findings')
    op.create_unique_constraint('static_findings_submission_id_key', 'static_findings', ['submission_id'])
    op.alter_column('static_findings', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_risk_verdicts_submission_id'), table_name='risk_verdicts')
    op.create_unique_constraint('risk_verdicts_submission_id_key', 'risk_verdicts', ['submission_id'])
    op.drop_index(op.f('ix_ml_scores_submission_id'), table_name='ml_scores')
    op.create_unique_constraint('ml_scores_submission_id_key', 'ml_scores', ['submission_id'])
    op.drop_index(op.f('ix_llm_reports_submission_id'), table_name='llm_reports')
    op.create_unique_constraint('llm_reports_submission_id_key', 'llm_reports', ['submission_id'])
    op.alter_column('llm_reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_dynamic_findings_submission_id'), table_name='dynamic_findings')
    op.create_unique_constraint('dynamic_findings_submission_id_key', 'dynamic_findings', ['submission_id'])
    op.alter_column('dynamic_findings', 'run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cluster_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaign_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_apk_submissions_uploaded_by'), table_name='apk_submissions')
    op.drop_index(op.f('ix_apk_submissions_status'), table_name='apk_submissions')
    op.drop_index(op.f('ix_apk_submissions_sha256_hash'), table_name='apk_submissions')
    op.create_index('ix_submissions_uploaded_by', 'apk_submissions', ['uploaded_by'], unique=False)
    op.create_index('ix_submissions_status', 'apk_submissions', ['status'], unique=False)
    op.create_index('ix_submissions_sha256', 'apk_submissions', ['sha256_hash'], unique=False)
    op.drop_column('apk_submissions', 'analysis_stages')
    # ### end Alembic commands ###
